name: Github to Nexus
on:
  push:
    branches: [ master ]
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: GPG_PRIVATE_KEY
          gpg-passphrase: GPG_PASSPHRASE
          
      - name: Publish package
        run: mvn -Psign,github2Nexus -DskipTests -Darguments=-DskipTests --no-transfer-progress --batch-mode clean deploy 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }} # for tests
