# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        git config --global http.postBuffer 157286400
        git clone https://github.com/thiagolvlsantos/gitt-example-projects.git
        ls -la gitt-example-projects
        mvn -U -B package --file pom.xml
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
